services:
  client:
    container_name: auth-app-client
    env_file:
      - ./client/.env
    build:
      context: ./client
    restart: always
    ports:
      - 3000:3000
    networks:
      - auth-app-network

  server:
    container_name: auth-app-server
    env_file:
      - ./server/.env
    build:
      context: ./server
    restart: always
    ports:
      - 3001:3000
    networks:
      - auth-app-network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  auth-app-network:
    external: true
